-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgJaNBpU8usSlWbLRA
DvZaz3piLH7i5iuVPnDXbGDJiyKgCgYIKoZIzj0DAQehRANCAAQACIJ4EDY3lE5P
cj5pxygjDQ76fskP7B/PzHqHsEv95AgXoI7fo+WNFJG7AiwaAWNFlX2hNT+O3h4n
2Vb2LIgE
-----END PRIVATE KEY-----